### analyze

// Variables section - defines variables to use in the request
@host = localhost
@port = 8080
@baseUrl = http://{{host}}{{#if port}}:{{port}}{{/if}}

// Path parameters
@id = REPLACE_WITH_ID_VALUE

POST {{baseUrl}}/widgets/{{id}}/analyze
Content-Type: application/json

// No body model found for this request